#!/bin/bash
function t0020 {
    FUSE_MD5=`e4test_mountpoint_struct_md5`
}

function t0020-check {
    [ "$FUSE_MD5" = "$DIRS_MD5" ]
}

set -e
source `dirname $0`/lib.sh

e4test_make_LOGFILE
e4test_make_FS 128
e4test_make_MOUNTPOINT

e4test_mount
mkdir -p $MOUNTPOINT/dir{a,b,c,d,e,f}{a,b,c,d,e,f}/dir{a,b,c,d,e,f}{a,b,c,d,e,f}/{0,1,2,3,4,5,6,7,8,9}
DIRS_MD5=`e4test_mountpoint_struct_md5`
e4test_umount

e4test_fuse_mount
e4test_run t0020
e4test_fuse_umount

rm $FS

e4test_end t0020-check
